### ISSUE TITLE
requirements_gpu.txt missing / deprecated?

### ISSUE THREAD

**Issue by joedeveloper** [ashrefm/multi-label-soft-f1#1]
Thank you so much for this!
This is the first tutorial re ML I have undertaken and it was an absolute pleasure.

The model training time was expected, but I'd like to do what I can to reduce it going forwards.
In the [readme.md](
https://github.com/ashrefm/multi-label-soft-f1/blame/master/README.md#L16) it mentions a requirements_gpu.txt file, any hints?

**Comment by ashrefm** [comment]
Hi Joe,
Thank you for your interest! I would happy to help you.
You mentioned the requirements_gpu.txt file that I forgot to commit. It is done now ;)
If you want to train the model using an Nvidia GPU you need to install CUDA drivers and tensorflow-gpu library. Please have a look at this link as it may help you configure your environement https://www.tensorflow.org/install/gpu
Best,
