### ISSUE TITLE
issue about utils and function-download_parallel not work

### ISSUE THREAD

**Issue by rslu2000** [ashrefm/multi-label-soft-f1#4]
Dear Author,

Something wrong in my implement process.
First the code "from utils import *" it is work, but when go down to the code 'movies = download_parallel(movies, destination)' then it happened 'NameError'.

The error info is as following:
'NameError: name 'download_parallel' is not defined.'

I sured that I have installed the correct package-'utils-1.0.1' by using typing  code-'pip3 install utils' under my terminal environment.

by the way, when I in Kaggle environment, I wrote one line code- 'from utils import *', it didn't work. The result showed that 'ModuleNotFoundError: No module named 'utils''.

I don't know why?
<img width="1421" alt="截圖 2020-07-03 下午4 45 02" src="https://user-images.githubusercontent.com/22634146/86451053-f2fc3300-bd4c-11ea-8c32-cf8763e5c1a1.png">

Could you give me some instructions?

Thanks a lot.
<img width="1057" alt="截圖 2020-07-03 下午4 43 10" src="https://user-images.githubusercontent.com/22634146/86450546-4d48c400-bd4c-11ea-857c-1a3ad715b1a7.png">

**Comment by ashrefm** [comment]
Hello,
As you installed the utils python package with pip, it may have conflicted with utils.py in this repo which is a custom made python module that contains the useful functions for this project. If you do not want to set up your environment like described in the README file, you could try a fix by renaming utils.py file to my_utils.py for example and then change the import in the python notebook consequently with this new name. Please, let me know if this helps you solve the bug you are facing.

**Comment by rslu2000** [comment]
Dear Author,

Based on your suggestion, I renamed the file utils.py as  my_utils.py and then it worked.
Thanks for your kindness and help.

-Raymod Lu
